apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hxfk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-hxfk@sha256:ceba0669f77a8166f1d5fc1c0bd47d023eabbe9219a9a0ed67dd991a611703b9
        name: my-nodejs
        resources: {}
status: {}
